# Generated by Django 5.0.2 on 2024-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('choice_1', models.CharField(max_length=500)),
                ('choice_2', models.CharField(max_length=500)),
                ('choice_3', models.CharField(max_length=500)),
                ('choice_4', models.CharField(max_length=500)),
                ('correct_response', models.CharField(max_length=500)),
            ],
        ),
    ]
