# Generated by Django 5.0.2 on 2024-02-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
